version: '3'
services:
  tomcat:
    build: .
    ports:
      - "8181:8080"
    command: ["catalina.sh", "run"]
    volumes:
      - tomcat-uploads:/usr/local/tomcat/webapps/glscandb/Uploads

volumes:
  tomcat-uploads:
    external: true
